spring.application.name=BackEnd
spring.datasource.url = jdbc:mysql://localhost:3306/digitalartgallery?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username = root
spring.datasource.password = Ijse@1234
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto = update
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.jpa.open-in-view = false
spring.jpa.show-sql = true
spring.main.allow-bean-definition-overriding = true
jwt.secret = 2G4M519R859617556C58820196374038792F423F7820192B4B6250781368566DF423Y6428472B4B6250969070166D
server.port = 8080

# Spring Boot Actuator Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Spring Security OAuth2 Client Configuration
spring.security.oauth2.client.registration.google.client-id=624860176860-vfp0d6pel24u8lhvvfdbbm3ptgac4rku.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

# Spring Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=virajdilshan2019@gmail.com
spring.mail.password=kcxa yqnx kuwo tafu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

